[server]
headless = true
address = "0.0.0.0"
port = 8501
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#22C7D6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
